---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/nuitdebout
    main_domain: reseau.nuitdebout.dev
    sys_packages:
      - mcrypt
      - vim
    php_packages:
      - { name: dev, package: php5-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
    php_extensions: ~
    php_ppa: php5
    database:
      name:     nuitdebout
      user:     root
      password: leurfairepeur
  roles:
    - init
    - nginx
    - php5-fpm
    - php5-cli
    - php5-common
    - mysql
    - curl
    - wget
    - git
